/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "on-primary-container": "#858383",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdea5",
        "inverse-surface": "#2f3031",
        "on-tertiary-fixed": "#261900",
        "inverse-on-surface": "#f2f0f0",
        "on-surface-variant": "#444748",
        "inverse-primary": "#c8c6c5",
        "surface-variant": "#e3e2e2",
        "surface": "#faf9f9",
        "outline": "#747878",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e8e8",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad9",
        "on-error": "#ffffff",
        "outline-variant": "#c4c7c7",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e3e2e0",
        "background": "#faf9f9",
        "on-secondary-fixed-variant": "#464745",
        "surface-container": "#efeded",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#5d4201",
        "secondary-container": "#e0e0dd",
        "surface-bright": "#faf9f9",
        "surface-tint": "#5f5e5e",
        "on-secondary-container": "#626361",
        "primary": "#000000",
        "secondary": "#5e5f5d",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-container": "#a17f3b",
        "primary-container": "#1c1b1b",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c7c6c4",
        "tertiary-container": "#261900",
        "on-secondary-fixed": "#1a1c1a",
        "surface-container-highest": "#e3e2e2",
        "on-primary-fixed-variant": "#474746",
        "tertiary-fixed-dim": "#e9c176",
        "surface-container-low": "#f4f3f3"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "none": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "section-gap": "128px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "mono-technical": ["Courier Prime", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-xl": ["80px", { "lineHeight": "96px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "mono-technical": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
